# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js LTS as the base image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --ignore-scripts --omit-dev

# Copy source code
COPY . .

# Build the package
RUN npm run build

# Install package globally
RUN npm link

# Minimal image for runtime
FROM node:18-alpine

# Create app directory and install express
WORKDIR /app
RUN npm init -y && npm install express

# Copy built package from builder stage
COPY scripts/notion-openapi.json /usr/local/scripts/
COPY --from=builder /usr/local/lib/node_modules/@notionhq/notion-mcp-server /usr/local/lib/node_modules/@notionhq/notion-mcp-server
COPY --from=builder /usr/local/bin/notion-mcp-server /usr/local/bin/notion-mcp-server

# Set default environment variables
ENV OPENAPI_MCP_HEADERS="{}"

# Set HTTP server
EXPOSE 3000
CMD ["node", "-e", "const express = require('express'); const { spawn } = require('child_process'); const app = express(); app.use(express.json()); app.get('/', (req, res) => res.json({status: 'ok', service: 'notion-mcp'})); app.post('/mcp', async (req, res) => { try { const mcpProcess = spawn('notion-mcp-server', [], { stdio: ['pipe', 'pipe', 'pipe'] }); mcpProcess.stdin.write(JSON.stringify(req.body) + '\\n'); mcpProcess.stdin.end(); let output = ''; mcpProcess.stdout.on('data', (data) => { output += data.toString(); }); mcpProcess.on('close', () => { try { res.json(JSON.parse(output)); } catch (e) { res.status(500).json({ error: 'Invalid JSON response' }); } }); } catch (error) { res.status(500).json({ error: error.message }); } }); app.listen(3000, () => console.log('HTTP server running on port 3000'));"]
