# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js LTS as the base image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --ignore-scripts --omit-dev

# Copy source code
COPY . .

# Build the package
RUN npm run build

# Install package globally
RUN npm link

# Minimal image for runtime
FROM node:18-alpine

# Install express for HTTP server
RUN npm install -g express

# Copy built package from builder stage
COPY scripts/notion-openapi.json /usr/local/scripts/
COPY --from=builder /usr/local/lib/node_modules/@notionhq/notion-mcp-server /usr/local/lib/node_modules/@notionhq/notion-mcp-server
COPY --from=builder /usr/local/bin/notion-mcp-server /usr/local/bin/notion-mcp-server

# Set default environment variables
ENV OPENAPI_MCP_HEADERS="{}"

# Set HTTP server
EXPOSE 3000
CMD ["node", "-e", "const express = require('express'); const app = express(); app.get('/', (req, res) => res.json({status: 'ok', service: 'notion-mcp'})); app.listen(3000, () => console.log('HTTP server running on port 3000'));"]
